-- San José
USE WWI_Sucursal_SJ;
GO
CREATE ROLE ADMINISTRADOR_SUCURSAL;

GRANT SELECT ON SCHEMA::Sales       TO ADMINISTRADOR_SUCURSAL;      -- Invoices (lectura)
GRANT SELECT ON SCHEMA::Purchasing  TO ADMINISTRADOR_SUCURSAL;      -- Suppliers (lectura)
GRANT SELECT ON SCHEMA::Warehouse   TO ADMINISTRADOR_SUCURSAL;      -- StockItems (lectura)

GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItems TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItemTransactions TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItemHoldings TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.SupplierTransactions TO ADMINISTRADOR_SUCURSAL;
GO

EXEC sp_addrolemember 'ADMINISTRADOR_SUCURSAL', 'admin_sucursal';
GO

-- Limón
USE WWI_Sucursal_LIM;
GO
CREATE ROLE ADMINISTRADOR_SUCURSAL;

GRANT SELECT ON SCHEMA::Sales       TO ADMINISTRADOR_SUCURSAL;      -- Invoices (lectura)
GRANT SELECT ON SCHEMA::Purchasing  TO ADMINISTRADOR_SUCURSAL;      -- Suppliers (lectura)
GRANT SELECT ON SCHEMA::Warehouse   TO ADMINISTRADOR_SUCURSAL;      -- StockItems (lectura)

GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItems TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItemTransactions TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.StockItemHoldings TO ADMINISTRADOR_SUCURSAL;
GRANT INSERT, UPDATE, DELETE ON OBJECT::Warehouse.SupplierTransactions TO ADMINISTRADOR_SUCURSAL;
GO
EXEC sp_addrolemember 'ADMINISTRADOR_SUCURSAL', 'admin_sucursal';
GO

-- Corporativo
USE WWI_Corporativo;
GO

CREATE ROLE CORPORATIVO;
GO

GRANT SELECT ON SCHEMA::Corp TO CORPORATIVO;
GO

-- Dar permisos, EXECUTE de forma granular:

EXEC sp_addrolemember 'CORPORATIVO', 'corp_user';
GO
